export default Object.freeze({
  COMPANY: 'कंपनी का नाम',
  BILL: 'बिल',
  ITEM_NAME: 'वस्तु का नाम',
  PRICE: 'कीमत',
  QUANTITY: 'मात्रा',
  MENU: 'मेन्यू',
  RESET_PASSWORD: 'पासवर्ड रीसेट',
  CUSTOMER: 'ग्राहक',
  EDIT_CUSTOMER: 'ग्राहक संपादित करें',
  ITEMS: 'सामान',
  EDIT_ITEM: 'वस्तु संपादन करें',
  ADD_ITEM: 'वस्तु जोड़ें',
  TOTAL: 'कुल',
  SETTINGS: 'सेटिंग',
  CUSTOMER_LIST: 'ग्राहकू सूची',
  ITEM_LIST: 'सामान की सूची',
  LOGIN: 'लॉग इन करें',
  LOGOUT: 'लॉग आउट करें',
  REGISTER: 'रजिस्टर करें',
  CREATE_BILL: 'बिल बनाएं',
  PAY_BILL: 'पैसा भरें',
  SELECT_PERSON: 'ग्राहक का चयन करें',
  SELECT_ITEM: 'वस्तु का चयन करें',
  SEARCH: 'खोजें...',
  HASTE: 'हस्ते',
  SAVE: 'सेव करे',
  CANCEL: 'रद्द करें',
  ADD: 'जोड़ें',
  OK: 'ठीक है',
  SUBMIT_CHANGES: 'परिवर्तन सबमिट करें',
  NAME: 'नाम',
  MOBILE_NO: 'मोबाइल नंबर',
  PREVIOUS_BILL: 'पिछला बिल',
  NO_PREVIOUS_BILL: 'कोई पिछला बिल नहीं है',
  BILL_DUE: 'बकाया बिल',
  CONTACTS: 'संपर्क',
  VIEW: 'देखें',
  GO_BACK: 'पीछे जाओ',
  SHARE: 'शेयर करें',
  EMAIL: 'ईमेल',
  PASSWORD: 'पासवर्ड',
  AMMOUNT: 'राशि',
  DATE: 'तारीख',
  FILTER: 'फिल्टर',
  VIEW_ORDERS: 'आर्डर और भुगतान देखें',
  VIEW_ORDERS: 'आर्डर और भुगतान देखें',
  PAYMENTS_TABLE: 'भुगतान तालिका',
  ORDERS_TABLE: 'आर्डर तालिका',
  ORDERS_TABLE: 'आर्डर तालिका',
  Customa: 'आर्डर तालिका',
  NEW_PASSWORD: 'नया पासवर्ड टाइप करें',
  AMMOUNT_TO_PAY: 'भुगतान की जाने वाली राशि टाइप करें',
  REMAINING_AMMOUNT_TO_PAY: 'भुगतान करने के लिए शेष राशि',
  NAME_REQUIRED_ERROR: 'नाम एक आवश्यक फ़ील्ड है',
  MOBILE_NO_ERROR: 'मोबाइल नंबर 10 अक्षरों का होना चाहिए',
  MOBILE_NO_REQUIRED_ERROR: 'मोबाइल नंबर एक आवश्यक फ़ील्ड है',
  BILL_REQUIRED_ERROR: 'बिल एक आवश्यक फ़ील्ड है',
  PRICE_REQUIRED_ERROR: 'कीमत एक आवश्यक फ़ील्ड है',
  EMAIL_REQUIRED_ERROR: 'ईमेल एक आवश्यक फ़ील्ड है',
  EMAIL_VALIDATION_ERROR: 'ईमेल एक मान्य ईमेल होना चाहिए',
  PASSWORD_REQUIRED_ERROR: 'पासवर्ड एक आवश्यक फ़ील्ड है',
  PASSWORD_MIN_ERROR: 'पासवर्ड कम से कम 6 अंकों का होना चाहिए',
  ALERT: 'चेतावनी',
  ALERT_LESS_AMMOUNT: 'कृपया बकाया बिल से कम या उसके बराबर राशि चुनें',
  ALERT_HASTE: 'राशि और हस्ते आवश्यक फ़ील्ड हैं',
  ALERT_WRONG_CUSTOMER: 'कृपया बकाया बिल वाला ग्राहक चुनें',
  ALERT_ADD_ITEM: 'कृपया वस्तु का चयन करें',
  ALERT_ADD_PERSON: 'कृपया ग्राहक का चयन करें',
  ALERT_ADD_HASTE: 'कृपया हस्ते डालें',
  ALERT_ADD_QUANTITY: 'कृपया मात्रा डालें',
  ALERT_NO_ORDERS_OR_PAYMENTS:
    'दी गई दिनांक सीमा में इस ग्राहक के लिए कोई आर्डर और भुगतान उपलब्ध नहीं है',
  ALERT_NO_PAYMENTS: 'कोई भुगतान उपलब्ध नहीं है',
  ALERT_NO_ORDERS: 'कोई आर्डर उपलब्ध नहीं है',
  ALERT_CUSTOMER_EXIST: 'दिए गए मोबाइल नंबर वाला ग्राहक पहले से मौजूद है',
  ERROR_NO_INTERNET: 'कोई इंटरनेट कनेक्शन नहीं है',
  ERROR_WRONG_PASSWORD: 'पासवर्ड गलत है',
  ERROR_WRONG_EMAIL: 'दिए गए ईमेल वाला कोई उपयोगकर्ता नहीं मिला',
  ERROR_USER_EXIST: 'यह ईमेल पहले से प्रयोग में है',
  ERROR_WEAK_PASSWORD: 'पासवर्ड बहुत कमजोर है',
  ERROR_WEAK_PASSWORD: 'पासवर्ड बहुत कमजोर है',
});
